troupon/account/tests/test_views.py, troupon/account/views.py
Unneeded reference to _auth module_ in _account/views.py_ was removed.
User property of _ForgotPasswordViewTestCase instance_  was renamed to _user_ from _registered_user_.
=> Fix use consistent variable names

.gitignore, troupon/.env.py, troupon/account/emails.py
moved mailgun api config details to .env file. Please merge.
=> fix-conceal-api-keys: 

.gitignore, circle.yml, troupon/staticfiles/.gitignore
Added commands to install Bower and the front-end dependencies on the CircleCI and Heroku deploys. Please merge.
=> Fix bower integration

.buildpacks, circle.yml
@chidi
This build adds nodejs buildpack
=> Fix production settings temp

circle.yml
@chidi
This build runs set buildpack from app folder
=> (fix) run command from app folder

circle.yml
@chidi please merge
This build fixes an error complaint on heroku about buildpack being already set. I think we are allowed to set buildpack once.
=> [#102839668] (fix) remove already set on app

package.json
Corrected structure of json. Please merge.
=> [#105570056] (fix) correct json structure

package.json
Build error resulting from package.json structure fixed.
Please merge.
=> [#105570056] (fix) generated json with jspkg.com generator

package.json
Added missing node engine in package.json.
Please merge.
=> [#105570056] (fix) add node engine

.bowerrc
This build configures bower to non-interactive mode when installing packages.
Please merge.
=> [#105570056] (fix) set bower to non-interactive

.gitignore, Procfile, troupon/static/bower_components/.gitignore
This build fixes an error with django-bower when 'bower_components' directory isn't present.
Please merge.
=> Add bower_components directory

requirements.txt, troupon/account/tests/test_views.py, troupon/deals/tests/test_views.py, troupon/troupon/settings/base.py
This build fixes incessant Circle CI timeout on tests. Testcases now run the PhantomJS browser once for each TestCase.
Please merge.
=> Fix circleci timeouts

troupon/templates/base.html
This build completes the signout functionality for this application.
An active link can be found on the base template and as such is included on all views.
Please merge.
=> [finishes #103949092] add signout URL in base template

troupon/account/views.py, troupon/deals/baseviews.py, troupon/deals/fixtures/initial_data.json, troupon/deals/models.py, troupon/deals/templates/deals/categories.html, troupon/deals/templates/deals/detail.html, troupon/deals/tests/test_models.py, troupon/deals/tests/test_routes.py, troupon/deals/urls.py, troupon/deals/views.py, troupon/static/css/deals.css, troupon/troupon/wsgi.py
This build handles UserDoesNotExist Exception.
It also sets a flash message if sign in errors are encountered when processing a sign in request.
Please merge.
=> Fix signin

README.md, troupon/deals/baseviews.py, troupon/deals/fixtures/initial_data.json, troupon/deals/models.py, troupon/deals/templates/deals/categories.html, troupon/deals/templates/deals/detail.html, troupon/deals/tests/test_models.py, troupon/deals/tests/test_routes.py, troupon/deals/urls.py, troupon/deals/views.py, troupon/static/css/deals.css, troupon/troupon/wsgi.py
This build resolves:
- Blank categories page
- inherits from View class for template rendering
- Deal Detail not been in semblance of mockup
- includes a discount method in Deal model
Please merge.
=> Feature deals by category

.gitignore, Gulpfile.js, README.md, package.json, troupon/static/css/base_styles.css, troupon/static/scss/base_styles.scss, troupon/static/scss/modules/_components.scss, troupon/static/scss/modules/_helpers.scss, troupon/static/scss/modules/_utils.scss, troupon/static/scss/modules/_variables.scss, troupon/static/scss/partials/_components.scss, troupon/static/scss/partials/_pages.scss, troupon/static/scss/partials/_resets.scss, troupon/static/scss/partials/_sections.scss, troupon/static/scss/partials/_typography.scss
This branch implements the Gulp-Sass workflow for using Sass in Troupon. It also adds a section to the README explaining the process. Please merge.
=> [#108941296] gulp-sass workflow

troupon/deals/fixtures/initial_data.json, troupon/deals/models.py, troupon/deals/tests/test_routes.py, troupon/deals/tests/test_views.py, troupon/deals/urls.py, troupon/deals/views.py
Trims unnecessary routes and allows access to single deal page through one route (_'/deal/<slug>'_).
Also, deal slug is terminated with timestamp to ensure that it is unique.
Please merge.
=> Fix deal slug

troupon/account/migrations/.gitignore, troupon/conversations/migrations/.gitignore, troupon/conversations/models.py, troupon/conversations/templates/conversations/compose.html, troupon/conversations/templates/conversations/detail.html, troupon/conversations/templates/conversations/index.html, troupon/conversations/views.py, troupon/static/css/base_styles.css, troupon/static/scss/partials/_pages.scss, troupon/static/scss/partials/_sections.scss
This request:
Fixes bug with compose
Applies font-weight to unread messages
Updates message listing logic
Please merge
=> Fix messaging

troupon/authentication/views.py
- Finish documentation on views in authentication app
=> [Chore #112217607] Document the Views in authentication app.

troupon/account/urls.py, troupon/authentication/urls.py, troupon/deals/urls.py, troupon/merchant/urls.py
Add documentation for  urls in: 
- *account* app
- *authentication* app
- *deals* app
- *merchant* app
=> [Chore #112217455] document urls project-wide

troupon/authentication/emails.py
This PR documents emails.py in the authentication app.
Please merge.
=> [Chore #111590166] Document emails.py in the authentication app.

troupon/account/models.py
Model class and methods properly documented.
=> [Chore #111761858] Document models.py in account app

troupon/authentication/forms.py
Finished documenting forms.py in authentication app
=> [Chore #112217057] Document forms.py in authentication app

.gitignore, requirements.txt, troupon/account/migrations/.gitignore, troupon/account/migrations/0001_initial.py, troupon/account/views.py, troupon/cart/templates/cart/cart.html, troupon/cart/tests.py, troupon/cart/tests/test_routes.py, troupon/cart/tests/test_views.py, troupon/cart/urls.py, troupon/cart/views.py, troupon/conversations/migrations/.gitignore, troupon/conversations/migrations/0001_initial.py, troupon/deals/migrations/0001_initial.py, troupon/deals/migrations/0002_auto_20160309_1220.py, troupon/deals/models.py, troupon/deals/templates/deals/detail.html, troupon/merchant/migrations/0001_initial.py, troupon/payment/migrations/0001_initial.py, troupon/payment/migrations/0002_auto_20160309_1250.py, troupon/static/css/base_styles.css, troupon/static/scss/partials/_components.scss, troupon/templates/base.html, troupon/templates/snippet_deal_thumbnail.html, troupon/troupon/settings/base.py
Adds the cart functionality namely: Adding items to the cart, Viewing a cart and Removing items from the cart.
Changes made in troupon/cart/urls.py 
* When viewing the deals in the home page, click on one of the deals and add to cart.
* When viewing a cart, there are three options available: 
* Remove the item from the cart: You can click on remove to remove a single item from the cart.
* Clear cart entirely: This action removes all the items in the cart.
* View the cart: This action redirects the user to the cart view page where they can proceed to checkout.
Finishes #115129305:  https://www.pivotaltracker.com/story/show/115129305
=> #115129305 Add to cart functionality

package.json, troupon/payment/templates/payment/confirmation.html, troupon/payment/views.py, troupon/static/css/base_styles.css, troupon/static/scss/partials/_pages.scss
It confirms the payment of the user by showing a success or an error message.
Confirmation.html in the payment app
On the deals page, you can click a deal and buy it, then pay with card. You will then be redirected to the confirmation page.
=> #115129357 Add payment status page

requirements.txt, troupon/account/api.py, troupon/account/serializers.py, troupon/cart/api.py, troupon/cart/serializers.py, troupon/deals/api.py, troupon/deals/serializers.py, troupon/merchant/api.py, troupon/merchant/serializers.py, troupon/payment/api.py, troupon/payment/serializers.py, troupon/troupon/api.py, troupon/troupon/settings/base.py
It creates the initial boilerplate for the Django Rest Framework.
* Installation of the DRF python module and addition or `rest_framework` to the settings `base.py`. 
* The URLs for the APIs should be defined in `troupon/troupon/api.py` on the base Troupon app.
* Various apps should have an `api.py` to define their respective API Views, and a `serializers.py` to define a serializer(s) for their respective model(s).
This cannot be manually tested since no endpoints are defined yet.
#113821767
=> #113821767 Create Initial DRF Boilerplate

troupon/cart/tests/test_routes.py, troupon/cart/tests/test_views.py, troupon/merchant/tests/test_views.py
This PR adds in Selenium tests for the cart feature
Add in Selenium tests for the Cart Feature
Run ``python manage.py test cart``
#115594799
=> #115594799 Add in Selenium tests for the Cart Feature

troupon/merchant/api.py, troupon/merchant/serializers.py, troupon/merchant/tests/test_api.py, troupon/payment/api.py, troupon/payment/fixtures/purchases.json, troupon/payment/serializers.py, troupon/payment/tests/test_api.py, troupon/troupon/api.py
This PR introduces API endpoints which allow registered merchants to see transactions.
Actions supported include:
- Listing all transactions: `GET /api/transactions/`
- Getting details of an individual transaction: `GET /api/transaction/<transaction_id>`
- Deleting a transaction: `DELETE /api/transaction/<transaction_id>`
The task required the creation of API endpoints using `django-rest-framework` which would enable a merchant to perform operations on Transactions.
Using a registered merchant's account, you can send requests to the API endpoints using:
- `POSTMAN`
- Inbuilt browsable API - This can be accessed by going to the API endpoints on any browser starting with endpoint `/api/transactions/`.
The API documentation is available on [Apiary](http://docs.troupon.apiary.io/)
#116192375
=> #116192375 Create transactions REST endpoints

troupon/merchant/templates/merchant/transactions.html, troupon/payment/admin.py, troupon/payment/models.py, troupon/payment/templates/payment/confirmation.html
This PR introduces fixes to the following bugs:
- Merchant can't see table header if there are no transactions
- App crash on OTP verification not present when admin email is set
- Buttons on success page after payment redirect properly
- As a registered merchant, go to your dashboard and click "Transactions"
- Create a new merchant and verify OTP
- Buy a deal and after purchasing, click the go back to deals button.
#118906705
=> #118906705 Fix miscellaneous bugs

troupon/authentication/templates/authentication/register.html, troupon/authentication/views.py, troupon/static/css/page_styles.css
This PR fixes the activation email message bug
On creating a new account on the application, a notification is displayed which says:
> You have successfully registered. A mail has been sent to your email address Invalid signin parameters. Possible causes might be: an incorrect username, an incorrect password or inexistent user account. Follow the link in the mail to activate your account
This notification is repeated 2 times, then also, a third notification which reads "You have successfully registered.
This PR solves the above problems.
By registering a new user with the correct credentials and without to view how the error messages are displayed.
#118911495
=> New Account Registration Message Bug

troupon/deals/tests/test_views.py
Add end to end tests for the Deals app.
Write Selenium tests for the following:
- Deal listing view
- Deal search view
- Deal detail view
Clone the repository, cd into it, and run `python manage.py test deals`.
#120098257
=> #120098257 E2E Testing for Deals App

README.md, gulpfile.js, package.json, troupon/account/templates/account/profile_base.html, troupon/account/templates/account/transaction.html, troupon/account/urls.py, troupon/account/views.py, troupon/payment/fixtures/purchases.json, troupon/payment/migrations/0002_purchases_user.py, troupon/payment/models.py
This PR displays the users transaction history.
From within the account page, a user can see history of all purchases via the History tab
By clicking on the user profile dashboard, you will be able to view all the transactions.
#108849054
=> #108849054 User Transaction History

troupon/static/scss/partials/_typography.scss, troupon/troupon/settings/production.py
This P.R fixes migrations issue.
=> [Fix] remove postgrespool

troupon/payment/views.py
This PR fixes the error on payment page error
When a user buys an item they get an error message
#108849054
=>  Fix payment error #108849054

troupon/authentication/tests/test_views.py
This PR implements E2E tests for the authentication app.
Write selenium tests for the following:
* Login functionality; and
* Register functionality
Clone the repository, cd into it and navigate to troupon. Then run:
```python manage.py test authentication/tests/test_views.py```
#120098195
=> [Chore #120098195] Implement E2E testing for the authentication app

troupon/merchant/templates/merchant/deal.html, troupon/static/js/merchant.js
This PR fixes the "Edit Deal" button in the merchant dashboard. Additionally, it modifies the styling of buttons on the merchant dashboard.
- Fix "Edit Deal" link in the merchant dashboard
- Ensure deal can be edited
- Run the application. 
- Login as a merchant. 
- Create a deal. 
- Edit the deal. 
#119716459
=> #119716459 Edit Deal Link

troupon/account/migrations/0008_auto_20160627_1736.py, troupon/authentication/templates/authentication/activation_successful.html, troupon/authentication/tests/test_routes.py, troupon/authentication/views.py, troupon/deals/migrations/0009_auto_20160627_1736.py, troupon/static/css/base_styles.css, troupon/static/scss/modules/_variables.scss, troupon/static/scss/partials/_components.scss
This PR sends feedback to users on successful activation.
* Create HTML file that displays feedback
* Modify view function to render a page rather than redirect to the login page.
* Write a test to verify functionality.
* Register on the Troupon site.
* Click the activation link sent to your mail.
* This should take you to a page telling you activation is successful.
#121394333
=> [Fix #121394333] Send feedback to user on successful activation

troupon/deals/api.py, troupon/deals/templates/deals/index.html, troupon/deals/tests/test_api.py, troupon/deals/views.py, troupon/static/js/location.js, troupon/templates/base.html, troupon/troupon/api.py
This PR enables Troupon to detect user's location and display deals based on location
* Automatically detect user's location
* Display deals based on user's location
Go to Troupon Home page and a popup asking for user's location will be displayed. Select ALLOW and the deals will be filtered to match your location
#115582173
=> Ft user location awareness 115582173
